<?php

namespace Proxies\__CG__\Vlreleases\UserBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class GroupEmails extends \Vlreleases\UserBundle\Entity\GroupEmails implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Vlreleases\\UserBundle\\Entity\\GroupEmails' . "\0" . 'groupEmail', '' . "\0" . 'Vlreleases\\UserBundle\\Entity\\GroupEmails' . "\0" . 'createdBy', '' . "\0" . 'Vlreleases\\UserBundle\\Entity\\GroupEmails' . "\0" . 'createdDate', '' . "\0" . 'Vlreleases\\UserBundle\\Entity\\GroupEmails' . "\0" . 'id', '' . "\0" . 'Vlreleases\\UserBundle\\Entity\\GroupEmails' . "\0" . 'groupusers');
        }

        return array('__isInitialized__', '' . "\0" . 'Vlreleases\\UserBundle\\Entity\\GroupEmails' . "\0" . 'groupEmail', '' . "\0" . 'Vlreleases\\UserBundle\\Entity\\GroupEmails' . "\0" . 'createdBy', '' . "\0" . 'Vlreleases\\UserBundle\\Entity\\GroupEmails' . "\0" . 'createdDate', '' . "\0" . 'Vlreleases\\UserBundle\\Entity\\GroupEmails' . "\0" . 'id', '' . "\0" . 'Vlreleases\\UserBundle\\Entity\\GroupEmails' . "\0" . 'groupusers');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (GroupEmails $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setGroupEmail($groupEmail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGroupEmail', array($groupEmail));

        return parent::setGroupEmail($groupEmail);
    }

    /**
     * {@inheritDoc}
     */
    public function getGroupEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGroupEmail', array());

        return parent::getGroupEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedBy($createdBy)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedBy', array($createdBy));

        return parent::setCreatedBy($createdBy);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedBy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedBy', array());

        return parent::getCreatedBy();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedDate($createdDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedDate', array($createdDate));

        return parent::setCreatedDate($createdDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedDate', array());

        return parent::getCreatedDate();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function addGroupuser(\Vlreleases\UserBundle\Entity\GroupmailUsers $groupuser)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addGroupuser', array($groupuser));

        return parent::addGroupuser($groupuser);
    }

    /**
     * {@inheritDoc}
     */
    public function removeGroupuser(\Vlreleases\UserBundle\Entity\GroupmailUsers $groupuser)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeGroupuser', array($groupuser));

        return parent::removeGroupuser($groupuser);
    }

    /**
     * {@inheritDoc}
     */
    public function getGroupusers()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGroupusers', array());

        return parent::getGroupusers();
    }

}
