imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig','php']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
      cssPath: /Vl-releases2/web/css/
      fontsPath: /Vl-releases2/web/fonts/css/
      imagesPath: /Vl-releases2/web/images/
      jsPath: /Vl-releases2/web/js/
      baseUrl: /Vl-releases2/web/app_dev.php/
      userImagePath: /Vl-releases2/web/userPhotos/
      userThumbImagePath: /Vl-releases2/web/userPhotos/thumbs/
      userUploadPath: /Vl-releases2/web/UploadedFiles/
     
# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"
    
# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        mapping_types:
                    enum: string        
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true
    

# Swiftmailer Configuration
swiftmailer:
    transport: smtp
    host:      mx.valuelabs.net
    username:  surendra.yallabandi
    password:  ammananna
    port    :  25

parameters:    
    baseUrl: /Vl-releases2/web/app_dev.php/
    imagesPath: \userPhotos\
gregwar_image:
    throw_exception: false
    cache_dir:  cache

doctrine_migrations:
    dir_name: %kernel.root_dir%/DoctrineMigrations
    namespace: Application\Migrations
    table_name: migration_versions
    name: Application Migrations