<?php

namespace Proxies\__CG__\Vlreleases\UserBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Product extends \Vlreleases\UserBundle\Entity\Product implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Vlreleases\\UserBundle\\Entity\\Product' . "\0" . 'productname', '' . "\0" . 'Vlreleases\\UserBundle\\Entity\\Product' . "\0" . 'ownername', '' . "\0" . 'Vlreleases\\UserBundle\\Entity\\Product' . "\0" . 'os', '' . "\0" . 'Vlreleases\\UserBundle\\Entity\\Product' . "\0" . 'brand', '' . "\0" . 'Vlreleases\\UserBundle\\Entity\\Product' . "\0" . 'serialNumber', '' . "\0" . 'Vlreleases\\UserBundle\\Entity\\Product' . "\0" . 'version', '' . "\0" . 'Vlreleases\\UserBundle\\Entity\\Product' . "\0" . 'description', '' . "\0" . 'Vlreleases\\UserBundle\\Entity\\Product' . "\0" . 'createdDate', '' . "\0" . 'Vlreleases\\UserBundle\\Entity\\Product' . "\0" . 'lastModifiedDate', '' . "\0" . 'Vlreleases\\UserBundle\\Entity\\Product' . "\0" . 'active', '' . "\0" . 'Vlreleases\\UserBundle\\Entity\\Product' . "\0" . 'available', '' . "\0" . 'Vlreleases\\UserBundle\\Entity\\Product' . "\0" . 'id', '' . "\0" . 'Vlreleases\\UserBundle\\Entity\\Product' . "\0" . 'deviceStatus', '' . "\0" . 'Vlreleases\\UserBundle\\Entity\\Product' . "\0" . 'requesters', '' . "\0" . 'Vlreleases\\UserBundle\\Entity\\Product' . "\0" . 'assignedUsers', '' . "\0" . 'Vlreleases\\UserBundle\\Entity\\Product' . "\0" . 'createdBy', '' . "\0" . 'Vlreleases\\UserBundle\\Entity\\Product' . "\0" . 'category');
        }

        return array('__isInitialized__', '' . "\0" . 'Vlreleases\\UserBundle\\Entity\\Product' . "\0" . 'productname', '' . "\0" . 'Vlreleases\\UserBundle\\Entity\\Product' . "\0" . 'ownername', '' . "\0" . 'Vlreleases\\UserBundle\\Entity\\Product' . "\0" . 'os', '' . "\0" . 'Vlreleases\\UserBundle\\Entity\\Product' . "\0" . 'brand', '' . "\0" . 'Vlreleases\\UserBundle\\Entity\\Product' . "\0" . 'serialNumber', '' . "\0" . 'Vlreleases\\UserBundle\\Entity\\Product' . "\0" . 'version', '' . "\0" . 'Vlreleases\\UserBundle\\Entity\\Product' . "\0" . 'description', '' . "\0" . 'Vlreleases\\UserBundle\\Entity\\Product' . "\0" . 'createdDate', '' . "\0" . 'Vlreleases\\UserBundle\\Entity\\Product' . "\0" . 'lastModifiedDate', '' . "\0" . 'Vlreleases\\UserBundle\\Entity\\Product' . "\0" . 'active', '' . "\0" . 'Vlreleases\\UserBundle\\Entity\\Product' . "\0" . 'available', '' . "\0" . 'Vlreleases\\UserBundle\\Entity\\Product' . "\0" . 'id', '' . "\0" . 'Vlreleases\\UserBundle\\Entity\\Product' . "\0" . 'deviceStatus', '' . "\0" . 'Vlreleases\\UserBundle\\Entity\\Product' . "\0" . 'requesters', '' . "\0" . 'Vlreleases\\UserBundle\\Entity\\Product' . "\0" . 'assignedUsers', '' . "\0" . 'Vlreleases\\UserBundle\\Entity\\Product' . "\0" . 'createdBy', '' . "\0" . 'Vlreleases\\UserBundle\\Entity\\Product' . "\0" . 'category');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Product $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setProductname($productname)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProductname', array($productname));

        return parent::setProductname($productname);
    }

    /**
     * {@inheritDoc}
     */
    public function getProductname()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductname', array());

        return parent::getProductname();
    }

    /**
     * {@inheritDoc}
     */
    public function setOwnername($ownername)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOwnername', array($ownername));

        return parent::setOwnername($ownername);
    }

    /**
     * {@inheritDoc}
     */
    public function getOwnername()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOwnername', array());

        return parent::getOwnername();
    }

    /**
     * {@inheritDoc}
     */
    public function setOs($os)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOs', array($os));

        return parent::setOs($os);
    }

    /**
     * {@inheritDoc}
     */
    public function getOs()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOs', array());

        return parent::getOs();
    }

    /**
     * {@inheritDoc}
     */
    public function setBrand($brand)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBrand', array($brand));

        return parent::setBrand($brand);
    }

    /**
     * {@inheritDoc}
     */
    public function getBrand()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBrand', array());

        return parent::getBrand();
    }

    /**
     * {@inheritDoc}
     */
    public function setSerialNumber($serialNumber)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSerialNumber', array($serialNumber));

        return parent::setSerialNumber($serialNumber);
    }

    /**
     * {@inheritDoc}
     */
    public function getSerialNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSerialNumber', array());

        return parent::getSerialNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setVersion($version)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVersion', array($version));

        return parent::setVersion($version);
    }

    /**
     * {@inheritDoc}
     */
    public function getVersion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVersion', array());

        return parent::getVersion();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', array($description));

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', array());

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedDate($createdDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedDate', array($createdDate));

        return parent::setCreatedDate($createdDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedDate', array());

        return parent::getCreatedDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setLastModifiedDate($lastModifiedDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastModifiedDate', array($lastModifiedDate));

        return parent::setLastModifiedDate($lastModifiedDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getLastModifiedDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastModifiedDate', array());

        return parent::getLastModifiedDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setActive($active)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActive', array($active));

        return parent::setActive($active);
    }

    /**
     * {@inheritDoc}
     */
    public function getActive()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActive', array());

        return parent::getActive();
    }

    /**
     * {@inheritDoc}
     */
    public function setAvailable($available)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAvailable', array($available));

        return parent::setAvailable($available);
    }

    /**
     * {@inheritDoc}
     */
    public function getAvailable()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAvailable', array());

        return parent::getAvailable();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setDeviceStatus(\Vlreleases\UserBundle\Entity\ProductStatus $deviceStatus = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeviceStatus', array($deviceStatus));

        return parent::setDeviceStatus($deviceStatus);
    }

    /**
     * {@inheritDoc}
     */
    public function getDeviceStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeviceStatus', array());

        return parent::getDeviceStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function addRequester(\Vlreleases\UserBundle\Entity\ProductQueue $requesters)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addRequester', array($requesters));

        return parent::addRequester($requesters);
    }

    /**
     * {@inheritDoc}
     */
    public function removeRequester(\Vlreleases\UserBundle\Entity\ProductQueue $requesters)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeRequester', array($requesters));

        return parent::removeRequester($requesters);
    }

    /**
     * {@inheritDoc}
     */
    public function getRequesters()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRequesters', array());

        return parent::getRequesters();
    }

    /**
     * {@inheritDoc}
     */
    public function addAssignedUser(\Vlreleases\UserBundle\Entity\ProductStatus $assignedUsers)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAssignedUser', array($assignedUsers));

        return parent::addAssignedUser($assignedUsers);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAssignedUser(\Vlreleases\UserBundle\Entity\ProductStatus $assignedUsers)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAssignedUser', array($assignedUsers));

        return parent::removeAssignedUser($assignedUsers);
    }

    /**
     * {@inheritDoc}
     */
    public function getAssignedUsers()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAssignedUsers', array());

        return parent::getAssignedUsers();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedBy(\Vlreleases\UserBundle\Entity\User $createdBy = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedBy', array($createdBy));

        return parent::setCreatedBy($createdBy);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedBy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedBy', array());

        return parent::getCreatedBy();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategory(\Vlreleases\UserBundle\Entity\Category $category = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategory', array($category));

        return parent::setCategory($category);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategory()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategory', array());

        return parent::getCategory();
    }

}
